# Generated by Django 5.2.1 on 2026-03-04 11:55

import authapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceqr',
            name='time',
            field=models.TimeField(default=authapp.models.current_local_time),
        ),
    ]
