# Generated by Django 5.2.1 on 2026-03-04 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_attendanceqr_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceqr',
            name='kbc_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
