# Generated by Django 5.2.1 on 2026-03-07 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_attendanceqr_kbc_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendanceqr',
            name='kbc_id',
        ),
    ]
